students=["varsha","deeksha","champa","rithwik"]
print(students)
print("-----")
print(students[1])
print(students[-1])
students[2]="suru"
print(students)
students.append("baba")
students.append("sara")
students.append("rara")
students.append("ana")
print(students)
students.remove("suru")
print(f"Remove suru:{students}")
students.remove("ana")
print(f"Remove ana:{students}")
students.insert(1,"om")
students.insert(3,"ram")
students.insert(4,"sam")
students.insert(6,"dad")
students.insert(2,"mom")
print(students)
students.pop(3)
students.pop(5)
students.pop(7)
print(len(f" Length of list:{len(students)}"))
print(students.reverse())
print(students)
print(type(students))
